# This is a basic workflow to help you get started with Actions

name: CRMntp-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: Ender-events/pandoc@master
        with:
          args: '-s --toc -V toc-title="Table of contents" -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" --include-before-body cover.tex source/introduction.md source/tp*.md -H chapter-break.tex -o build/output.pdf'
